CREATE TABLE conta (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dono VARCHAR(60) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    senha CHAR(64) NOT NULL,
    saldo DECIMAL(15,2) DEFAULT 0
);